version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '14.16'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn install --ignore-engines
      - run: npm run build
      - run: npm run lint
workflows:
  build-and-test:
    jobs:
      - build-and-test
