version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn install
      - run: npm run build
      - run: npm run lint
workflows:
  build-and-test:
    jobs:
      - build-and-test
